<?php

namespace SmartCloudSolutions\GubarevBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends EntityRepository
{
    /**
     * Get holiday days
     *
     * @param int $year year to select by
     *
     * @return array set of holiday days of a year
     */
    public function getByYear($year)
    {
        $return = array();
        $query = 'SELECT data FROM Holiday'
            . ' WHERE YEAR(data) = :year';

        $params = array(
            'year' => $year
        );

        $result = $this->getEntityManager()->getConnection()->executeQuery($query, $params)->fetchAll();
        foreach ($result as $row) {
            $return[] = $row['data'];
        }

        return $return;
    }
}
