<?php

namespace SmartCloudSolutions\GubarevBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends EntityRepository
{
    /**
     * Get translation of a text
     *
     * @param string $text text to translate
     * @param string $lang language
     *
     * @return string translation
     */
    public function getTranslationByTextLang($text, $lang = 'ru')
    {
        $query = 'SELECT tr.text FROM Text AS t'
            . ' LEFT JOIN Translation AS tr ON t.id = tr. text_id'
            . ' WHERE t.text = :text AND tr.lang = :lang';

        $params = array(
            'text' => strtolower($text),
            'lang' => $lang
        );

        $result = $this->getEntityManager()->getConnection()->executeQuery($query, $params)->fetchAll();

        if (isset($result[0])) {
            return $result[0]['text'];
        }

        return $text;
    }
}
